import { type BatchCandidateReadinessRow } from "../../batch-readiness";
export declare function listBatches(input?: unknown): Promise<{
    rows: {
        batch: {
            id: number;
            sourceJobId: number | null;
            sourceDocumentId: number | null;
            entityId: number | null;
            protocolId: number | null;
            roleId: number | null;
            sourceType: string | null;
            sourceUrl: string | null;
            sourceName: string | null;
            confidenceDefault: number | null;
            qualityTierDefault: number | null;
            statusDefault: number | null;
            flagsDefault: number | null;
            importedCount: number;
            acceptedCount: number;
            rejectedCount: number;
            conflictCount: number;
            effectiveFromBlock: number | null;
            effectiveToBlock: number | null;
            labelAction: string;
            supersedesBatchId: number | null;
            batchHash: string | null;
            evidenceHash: string | null;
            storageUri: string | null;
            parserVersion: string;
            dictionaryVersion: string | null;
            status: string;
            createdBy: string | null;
            approvedBy: string | null;
            createdAt: Date;
            updatedAt: Date;
            approvedAt: Date | null;
            committedAt: Date | null;
        };
        entity: {
            id: number;
            entityCode: string;
            entityName: string;
            entityType: string | null;
            categoryId: number | null;
            websiteUrl: string | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        protocol: {
            id: number;
            entityId: number | null;
            protocolCode: string;
            protocolName: string;
            protocolType: string | null;
            chainScope: string[] | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        role: {
            roleId: number;
            roleCode: string;
            roleName: string;
            categoryId: number | null;
            roleGroup: string | null;
            metricUsageDefault: string | null;
            boundaryClass: string | null;
            defaultQualityTier: number;
            defaultFlags: number;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    }[];
    filters: {
        sort: "created_at" | "updated_at" | "status" | "accepted_count" | "committed_at";
        page: number;
        pageSize: number;
        q?: string | undefined;
        status?: string | undefined;
        sourceType?: string | undefined;
        entity?: string | undefined;
        protocol?: string | undefined;
        role?: string | undefined;
        labelAction?: string | undefined;
    };
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
}>;
export declare function getBatchDetail(batchId: number): Promise<{
    batch: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        entityId: number | null;
        protocolId: number | null;
        roleId: number | null;
        sourceType: string | null;
        sourceUrl: string | null;
        sourceName: string | null;
        confidenceDefault: number | null;
        qualityTierDefault: number | null;
        statusDefault: number | null;
        flagsDefault: number | null;
        importedCount: number;
        acceptedCount: number;
        rejectedCount: number;
        conflictCount: number;
        effectiveFromBlock: number | null;
        effectiveToBlock: number | null;
        labelAction: string;
        supersedesBatchId: number | null;
        batchHash: string | null;
        evidenceHash: string | null;
        storageUri: string | null;
        parserVersion: string;
        dictionaryVersion: string | null;
        status: string;
        createdBy: string | null;
        approvedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        approvedAt: Date | null;
        committedAt: Date | null;
    };
    candidates: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    candidateReadiness: BatchCandidateReadinessRow[];
    sourceJob: {
        id: number;
        sourceType: string;
        sourceName: string | null;
        sourceUrl: string | null;
        localFileName: string | null;
        archiveStorageUri: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        chainScope: string[] | null;
        expectedRoles: string[] | null;
        status: string;
        parserVersion: string;
        submittedBy: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    sourceDocument: {
        id: number;
        sourceJobId: number | null;
        documentType: string;
        originalName: string | null;
        storageUri: string | null;
        contentHash: string;
        mimeType: string | null;
        sizeBytes: number | null;
        extractedText: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    };
    entity: {
        id: number;
        entityCode: string;
        entityName: string;
        entityType: string | null;
        categoryId: number | null;
        websiteUrl: string | null;
        description: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    };
    protocol: {
        id: number;
        entityId: number | null;
        protocolCode: string;
        protocolName: string;
        protocolType: string | null;
        chainScope: string[] | null;
        description: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    };
    role: {
        roleId: number;
        roleCode: string;
        roleName: string;
        categoryId: number | null;
        roleGroup: string | null;
        metricUsageDefault: string | null;
        boundaryClass: string | null;
        defaultQualityTier: number;
        defaultFlags: number;
        description: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    };
    candidateEvidence: never[] | {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        evidenceType: string;
        sourceUrl: string | null;
        sourceDocumentId: number | null;
        evidenceHash: string | null;
        storageUri: string | null;
        confidenceDelta: number;
        trustTier: string;
        summary: string | null;
        payload: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
    }[];
    batchEvidence: {
        id: number;
        batchId: number | null;
        evidenceId: number | null;
        evidenceHash: string | null;
        summary: string | null;
        payload: Record<string, unknown>;
        createdAt: Date;
    }[];
    approvalEvents: {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        action: string;
        actorId: string | null;
        reason: string | null;
        beforeJson: Record<string, unknown> | null;
        afterJson: Record<string, unknown> | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    kvBuilds: {
        id: number;
        buildHash: string;
        dictionaryVersion: string | null;
        buildKind: string;
        baseBuildId: number | null;
        deltaParentBuildId: number | null;
        lastCommittedBatchId: number | null;
        status: string;
        rowCount: number;
        storageUri: string | null;
        manifest: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    }[];
    registryRows: {
        registry: {
            id: number;
            normalizedAddress: string;
            rawAddress: string | null;
            chainCode: string;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityId: number | null;
            protocolId: number | null;
            categoryId: number | null;
            roleId: number | null;
            componentId: number | null;
            tagsetId: number | null;
            confidenceScore: number;
            labelStatus: number;
            qualityTier: number;
            flags: number;
            metricUsage: string | null;
            validFromBlock: number | null;
            validToBlock: number | null;
            firstSeenBlock: number | null;
            lastSeenBlock: number | null;
            isActive: boolean;
            primarySourceJobId: number | null;
            approvedBatchId: number | null;
            notes: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        };
        entityName: string | null;
        protocolName: string | null;
        roleCode: string | null;
    }[];
    candidateRollup: {
        totalCandidates: number;
        acceptedCount: number;
        rejectedCount: number;
        conflictCount: number;
        duplicateCount: number;
        averageConfidence: number;
        qualityDistribution: {
            label: string;
            count: number;
        }[];
        confidenceDistribution: {
            label: string;
            count: number;
        }[];
        statusDistribution: {
            label: string;
            count: number;
        }[];
        firstSeenBlock: number | null;
        lastSeenBlock: number | null;
    };
    evidenceRollup: {
        totalEvidence: number;
        netConfidenceDelta: number;
        evidenceTypeDistribution: {
            label: string;
            count: number;
        }[];
        trustDistribution: {
            label: string;
            count: number;
        }[];
    };
    registryRollup: {
        totalRows: number;
        activeRows: number;
        inactiveRows: number;
        metricEligibleRows: number;
    };
} | null>;
export declare function createBatchFromCandidates(input: unknown): Promise<{
    id: number;
    createdAt: Date;
    updatedAt: Date;
    sourceType: string | null;
    sourceName: string | null;
    sourceUrl: string | null;
    status: string;
    parserVersion: string;
    sourceJobId: number | null;
    storageUri: string | null;
    entityId: number | null;
    approvedBy: string | null;
    approvedAt: Date | null;
    roleId: number | null;
    protocolId: number | null;
    createdBy: string | null;
    sourceDocumentId: number | null;
    confidenceDefault: number | null;
    qualityTierDefault: number | null;
    statusDefault: number | null;
    flagsDefault: number | null;
    importedCount: number;
    acceptedCount: number;
    rejectedCount: number;
    conflictCount: number;
    effectiveFromBlock: number | null;
    effectiveToBlock: number | null;
    labelAction: string;
    supersedesBatchId: number | null;
    batchHash: string | null;
    evidenceHash: string | null;
    dictionaryVersion: string | null;
    committedAt: Date | null;
}>;
export declare function approveBatch(input: unknown): Promise<{
    id: number;
    sourceJobId: number | null;
    sourceDocumentId: number | null;
    entityId: number | null;
    protocolId: number | null;
    roleId: number | null;
    sourceType: string | null;
    sourceUrl: string | null;
    sourceName: string | null;
    confidenceDefault: number | null;
    qualityTierDefault: number | null;
    statusDefault: number | null;
    flagsDefault: number | null;
    importedCount: number;
    acceptedCount: number;
    rejectedCount: number;
    conflictCount: number;
    effectiveFromBlock: number | null;
    effectiveToBlock: number | null;
    labelAction: string;
    supersedesBatchId: number | null;
    batchHash: string | null;
    evidenceHash: string | null;
    storageUri: string | null;
    parserVersion: string;
    dictionaryVersion: string | null;
    status: string;
    createdBy: string | null;
    approvedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    approvedAt: Date | null;
    committedAt: Date | null;
}>;
export declare function failBatch(input: unknown): Promise<{
    id: number;
    sourceJobId: number | null;
    sourceDocumentId: number | null;
    entityId: number | null;
    protocolId: number | null;
    roleId: number | null;
    sourceType: string | null;
    sourceUrl: string | null;
    sourceName: string | null;
    confidenceDefault: number | null;
    qualityTierDefault: number | null;
    statusDefault: number | null;
    flagsDefault: number | null;
    importedCount: number;
    acceptedCount: number;
    rejectedCount: number;
    conflictCount: number;
    effectiveFromBlock: number | null;
    effectiveToBlock: number | null;
    labelAction: string;
    supersedesBatchId: number | null;
    batchHash: string | null;
    evidenceHash: string | null;
    storageUri: string | null;
    parserVersion: string;
    dictionaryVersion: string | null;
    status: string;
    createdBy: string | null;
    approvedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    approvedAt: Date | null;
    committedAt: Date | null;
}>;
export declare function supersedeBatch(input: unknown): Promise<{
    id: number;
    sourceJobId: number | null;
    sourceDocumentId: number | null;
    entityId: number | null;
    protocolId: number | null;
    roleId: number | null;
    sourceType: string | null;
    sourceUrl: string | null;
    sourceName: string | null;
    confidenceDefault: number | null;
    qualityTierDefault: number | null;
    statusDefault: number | null;
    flagsDefault: number | null;
    importedCount: number;
    acceptedCount: number;
    rejectedCount: number;
    conflictCount: number;
    effectiveFromBlock: number | null;
    effectiveToBlock: number | null;
    labelAction: string;
    supersedesBatchId: number | null;
    batchHash: string | null;
    evidenceHash: string | null;
    storageUri: string | null;
    parserVersion: string;
    dictionaryVersion: string | null;
    status: string;
    createdBy: string | null;
    approvedBy: string | null;
    createdAt: Date;
    updatedAt: Date;
    approvedAt: Date | null;
    committedAt: Date | null;
}>;
export declare function commitBatch(input: unknown): Promise<{
    batch: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        entityId: number | null;
        protocolId: number | null;
        roleId: number | null;
        sourceType: string | null;
        sourceUrl: string | null;
        sourceName: string | null;
        confidenceDefault: number | null;
        qualityTierDefault: number | null;
        statusDefault: number | null;
        flagsDefault: number | null;
        importedCount: number;
        acceptedCount: number;
        rejectedCount: number;
        conflictCount: number;
        effectiveFromBlock: number | null;
        effectiveToBlock: number | null;
        labelAction: string;
        supersedesBatchId: number | null;
        batchHash: string | null;
        evidenceHash: string | null;
        storageUri: string | null;
        parserVersion: string;
        dictionaryVersion: string | null;
        status: string;
        createdBy: string | null;
        approvedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        approvedAt: Date | null;
        committedAt: Date | null;
    };
    registryIds: number[];
    dictionaryVersion: string;
}>;
export declare function getBatchCandidateCount(batchId: number): Promise<number>;
