export type IntakeSummary = {
    sourceJobId: number;
    totalRows: number;
    validAddresses: number;
    invalidAddresses: number;
    duplicates: number;
    candidatesCreated: number;
    candidatesUpdated: number;
    evidenceCreated: number;
    conflictsFound: number;
    errors: string[];
};
export declare function createManualIntake(formInput: unknown): Promise<IntakeSummary>;
export declare function createCsvIntake(formInput: unknown): Promise<IntakeSummary>;
export declare function createAiCleanedCsvIntake(formInput: unknown): Promise<IntakeSummary>;
export declare function createUrlIntake(formInput: unknown): Promise<IntakeSummary>;
export declare function createDeploymentSourceIntake(formInput: unknown): Promise<IntakeSummary>;
export declare function createJsonEvidenceIntake(formInput: unknown): Promise<IntakeSummary>;
export declare function listCandidatesFromDatabase(input?: unknown): Promise<{
    rows: {
        sourceVerificationContext: import("../../candidate-detail").CandidateSourceVerificationContext | null;
        candidate: {
            id: number;
            sourceJobId: number | null;
            sourceDocumentId: number | null;
            rawAddress: string;
            normalizedAddress: string;
            chainCode: string | null;
            addressFamily: string | null;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityHint: string | null;
            protocolHint: string | null;
            roleHint: string | null;
            suggestedEntityId: number | null;
            suggestedProtocolId: number | null;
            suggestedRoleId: number | null;
            suggestedComponentId: number | null;
            confidenceScore: number;
            qualityTier: number;
            candidateStatus: string;
            duplicateOfCandidateId: number | null;
            discoveredBy: string;
            discoveryJobId: number | null;
            evidenceCount: number;
            lastSeenBlock: number | null;
            firstSeenBlock: number | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        };
        entityName: string | null;
        protocolName: string | null;
        roleCode: string | null;
        sourceType: string | null;
    }[];
    filters: {
        sort: "created_at" | "evidence_count" | "confidence";
        page: number;
        pageSize: number;
        q?: string | undefined;
        chain?: string | undefined;
        entity?: string | undefined;
        protocol?: string | undefined;
        role?: string | undefined;
        status?: string | undefined;
        sourceType?: string | undefined;
        discoveryType?: string | undefined;
        conflicts?: "false" | "true" | undefined;
        minConfidence?: number | undefined;
        maxConfidence?: number | undefined;
        qualityTier?: number | undefined;
    };
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
}>;
export declare function getCandidateDetail(id: number): Promise<{
    candidate: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        suggestedComponentId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    evidence: {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        evidenceType: string;
        sourceUrl: string | null;
        sourceDocumentId: number | null;
        evidenceHash: string | null;
        storageUri: string | null;
        confidenceDelta: number;
        trustTier: string;
        summary: string | null;
        payload: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
    }[];
    dictionaries: {
        entityByKey: Map<string, {
            id: number;
            entityCode: string;
            entityName: string;
            entityType: string | null;
            categoryId: number | null;
            websiteUrl: string | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }>;
        protocolByKey: Map<string, {
            id: number;
            entityId: number | null;
            protocolCode: string;
            protocolName: string;
            protocolType: string | null;
            chainScope: string[] | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }>;
        roleByKey: Map<string, {
            roleId: number;
            roleCode: string;
            roleName: string;
            categoryId: number | null;
            roleGroup: string | null;
            metricUsageDefault: string | null;
            boundaryClass: string | null;
            defaultQualityTier: number;
            defaultFlags: number;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }>;
        entities: {
            id: number;
            entityCode: string;
            entityName: string;
            entityType: string | null;
            categoryId: number | null;
            websiteUrl: string | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
        protocols: {
            id: number;
            entityId: number | null;
            protocolCode: string;
            protocolName: string;
            protocolType: string | null;
            chainScope: string[] | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
        roles: {
            roleId: number;
            roleCode: string;
            roleName: string;
            categoryId: number | null;
            roleGroup: string | null;
            metricUsageDefault: string | null;
            boundaryClass: string | null;
            defaultQualityTier: number;
            defaultFlags: number;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
        categories: {
            categoryId: number;
            categoryCode: string;
            categoryName: string;
            parentCategoryId: number | null;
            domainCode: string | null;
            metricDomain: string | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
        prefixes: {
            prefixCode: number;
            chainCode: string;
            chainName: string | null;
            chainFamily: string;
            addressFamily: string;
            codec: string;
            payloadLen: number | null;
            evmChainId: number | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
        metricGroups: {
            id: number;
            metricGroupCode: string;
            metricGroupName: string;
            chainCode: string | null;
            namespaceId: number | null;
            minConfidence: number;
            requireMetricEligible: boolean;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        }[];
        metricGroupRules: {
            id: number;
            metricGroupId: number;
            ruleVersion: number;
            ruleJson: Record<string, unknown>;
            status: string;
            sourceId: number | null;
            contentHash: string | null;
            createdAt: Date;
            updatedAt: Date;
            activatedAt: Date | null;
            retiredAt: Date | null;
        }[];
    };
    sourceJob: {
        id: number;
        sourceType: string;
        sourceName: string | null;
        sourceUrl: string | null;
        localFileName: string | null;
        archiveStorageUri: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        chainScope: string[] | null;
        expectedRoles: string[] | null;
        status: string;
        parserVersion: string;
        submittedBy: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    sourceDocument: {
        id: number;
        sourceJobId: number | null;
        documentType: string;
        originalName: string | null;
        storageUri: string | null;
        contentHash: string;
        mimeType: string | null;
        sizeBytes: number | null;
        extractedText: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    };
    registryMatches: never[] | {
        registry: {
            id: number;
            normalizedAddress: string;
            rawAddress: string | null;
            chainCode: string;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityId: number | null;
            protocolId: number | null;
            categoryId: number | null;
            roleId: number | null;
            componentId: number | null;
            tagsetId: number | null;
            confidenceScore: number;
            labelStatus: number;
            qualityTier: number;
            flags: number;
            metricUsage: string | null;
            validFromBlock: number | null;
            validToBlock: number | null;
            firstSeenBlock: number | null;
            lastSeenBlock: number | null;
            isActive: boolean;
            primarySourceJobId: number | null;
            approvedBatchId: number | null;
            notes: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        };
        entity: {
            id: number;
            entityCode: string;
            entityName: string;
            entityType: string | null;
            categoryId: number | null;
            websiteUrl: string | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        protocol: {
            id: number;
            entityId: number | null;
            protocolCode: string;
            protocolName: string;
            protocolType: string | null;
            chainScope: string[] | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        role: {
            roleId: number;
            roleCode: string;
            roleName: string;
            categoryId: number | null;
            roleGroup: string | null;
            metricUsageDefault: string | null;
            boundaryClass: string | null;
            defaultQualityTier: number;
            defaultFlags: number;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        category: {
            categoryId: number;
            categoryCode: string;
            categoryName: string;
            parentCategoryId: number | null;
            domainCode: string | null;
            metricDomain: string | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    }[];
    approvalEvents: {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        action: string;
        actorId: string | null;
        reason: string | null;
        beforeJson: Record<string, unknown> | null;
        afterJson: Record<string, unknown> | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    duplicateOfCandidate: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        suggestedComponentId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    duplicateCandidates: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        suggestedComponentId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    discoveryJob: {
        id: number;
        discoveryType: string;
        status: string;
        chainCode: string | null;
        seedAddress: string | null;
        entityId: number | null;
        protocolId: number | null;
        config: Record<string, unknown>;
        candidatesCreated: number;
        evidenceCreated: number;
        error: string | null;
        logs: string[];
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
    };
    sourceVerifications: {
        verification: {
            id: number;
            sourceJobId: number | null;
            sourceDocumentId: number | null;
            candidateId: number | null;
            verificationScope: string;
            sourceSheet: string | null;
            sourceUrl: string | null;
            sourceTrust: string;
            status: string;
            notes: string | null;
            verificationEvidence: Record<string, unknown>;
            verifiedBy: string | null;
            createdAt: Date;
        };
        verifierEmail: string | null;
        verifierName: string | null;
    }[];
} | null>;
export declare function listApprovedCandidateIds(): Promise<{
    id: number;
}[]>;
export declare function getCandidatesByIds(candidateIds: number[]): Promise<{
    id: number;
    sourceJobId: number | null;
    sourceDocumentId: number | null;
    rawAddress: string;
    normalizedAddress: string;
    chainCode: string | null;
    addressFamily: string | null;
    prefixCode: number | null;
    namespaceId: number | null;
    addressCodecId: number | null;
    payloadHex: string | null;
    entityHint: string | null;
    protocolHint: string | null;
    roleHint: string | null;
    suggestedEntityId: number | null;
    suggestedProtocolId: number | null;
    suggestedRoleId: number | null;
    suggestedComponentId: number | null;
    confidenceScore: number;
    qualityTier: number;
    candidateStatus: string;
    duplicateOfCandidateId: number | null;
    discoveredBy: string;
    discoveryJobId: number | null;
    evidenceCount: number;
    lastSeenBlock: number | null;
    firstSeenBlock: number | null;
    metadata: Record<string, unknown>;
    createdAt: Date;
    updatedAt: Date;
}[]>;
