export declare function getDashboardOverviewFromDatabase(): Promise<{
    stats: {
        pendingCandidates: number;
        needsReview: number;
        approvedToday: number;
        rejectedToday: number;
        committedBatches: number;
        activeEntities: number;
        activeProtocols: number;
        activeLabels: number;
        unresolvedConflicts: number;
        metricEligibleCount: number;
        activeMetricGroups: number;
    };
    latestBatch: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        entityId: number | null;
        protocolId: number | null;
        roleId: number | null;
        sourceType: string | null;
        sourceUrl: string | null;
        sourceName: string | null;
        confidenceDefault: number | null;
        qualityTierDefault: number | null;
        statusDefault: number | null;
        flagsDefault: number | null;
        importedCount: number;
        acceptedCount: number;
        rejectedCount: number;
        conflictCount: number;
        effectiveFromBlock: number | null;
        effectiveToBlock: number | null;
        labelAction: string;
        supersedesBatchId: number | null;
        batchHash: string | null;
        evidenceHash: string | null;
        storageUri: string | null;
        parserVersion: string;
        dictionaryVersion: string | null;
        status: string;
        createdBy: string | null;
        approvedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        approvedAt: Date | null;
        committedAt: Date | null;
    };
    latestKvBuild: {
        id: number;
        buildHash: string;
        dictionaryVersion: string | null;
        buildKind: string;
        baseBuildId: number | null;
        deltaParentBuildId: number | null;
        lastCommittedBatchId: number | null;
        status: string;
        rowCount: number;
        storageUri: string | null;
        manifest: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    };
    latestKvBuildSummary: import("../../dashboard").DashboardLatestKvBuildSummary;
    discoveryStatus: {
        label: string;
        count: number;
    }[];
    sourceTypes: {
        label: string;
        count: number;
    }[];
    qualityTiers: {
        label: string;
        count: number;
    }[];
    confidenceDistribution: import("../../batch-detail").DistributionRow[];
    labelsByEntity: {
        label: string;
        count: number;
    }[];
    recentApprovalEvents: {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        action: string;
        actorId: string | null;
        reason: string | null;
        beforeJson: Record<string, unknown> | null;
        afterJson: Record<string, unknown> | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    recentSourceJobs: {
        id: number;
        sourceType: string;
        sourceName: string | null;
        sourceUrl: string | null;
        localFileName: string | null;
        archiveStorageUri: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        chainScope: string[] | null;
        expectedRoles: string[] | null;
        status: string;
        parserVersion: string;
        submittedBy: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    recentDiscoveryJobs: {
        id: number;
        discoveryType: string;
        status: string;
        chainCode: string | null;
        seedAddress: string | null;
        entityId: number | null;
        protocolId: number | null;
        config: Record<string, unknown>;
        candidatesCreated: number;
        evidenceCreated: number;
        error: string | null;
        logs: string[];
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[];
}>;
