export declare function listDiscoveryJobs(input?: unknown): Promise<{
    rows: {
        job: {
            id: number;
            discoveryType: string;
            status: string;
            chainCode: string | null;
            seedAddress: string | null;
            entityId: number | null;
            protocolId: number | null;
            config: Record<string, unknown>;
            candidatesCreated: number;
            evidenceCreated: number;
            error: string | null;
            logs: string[];
            createdBy: string | null;
            createdAt: Date;
            updatedAt: Date;
        };
        entity: {
            id: number;
            entityCode: string;
            entityName: string;
            entityType: string | null;
            categoryId: number | null;
            websiteUrl: string | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        protocol: {
            id: number;
            entityId: number | null;
            protocolCode: string;
            protocolName: string;
            protocolType: string | null;
            chainScope: string[] | null;
            description: string | null;
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        } | null;
    }[];
    filters: {
        sort: "created_at" | "updated_at" | "status" | "candidates_created" | "evidence_created";
        page: number;
        pageSize: number;
        q?: string | undefined;
        discoveryType?: string | undefined;
        status?: string | undefined;
        chain?: string | undefined;
        entity?: string | undefined;
        protocol?: string | undefined;
        seed?: string | undefined;
        minCandidates?: number | undefined;
        minEvidence?: number | undefined;
    };
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
}>;
export declare function getDiscoveryJob(id: number): Promise<{
    id: number;
    discoveryType: string;
    status: string;
    chainCode: string | null;
    seedAddress: string | null;
    entityId: number | null;
    protocolId: number | null;
    config: Record<string, unknown>;
    candidatesCreated: number;
    evidenceCreated: number;
    error: string | null;
    logs: string[];
    createdBy: string | null;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function getDiscoveryJobDetail(id: number): Promise<{
    completion: import("../../discovery-detail").DiscoveryCompletionSummary;
    candidateRollup: {
        totalCandidates: number;
        evidenceCount: number;
        approvedCount: number;
        pendingCount: number;
        duplicateCount: number;
        conflictCount: number;
        statusDistribution: import("../../batch-detail").DistributionRow[];
        chainDistribution: import("../../batch-detail").DistributionRow[];
        confidenceDistribution: import("../../batch-detail").DistributionRow[];
    };
    evidenceRollup: {
        totalEvidence: number;
        typeDistribution: import("../../batch-detail").DistributionRow[];
        trustDistribution: import("../../batch-detail").DistributionRow[];
    };
    logDistribution: import("../../batch-detail").DistributionRow[];
    job: {
        id: number;
        discoveryType: string;
        status: string;
        chainCode: string | null;
        seedAddress: string | null;
        entityId: number | null;
        protocolId: number | null;
        config: Record<string, unknown>;
        candidatesCreated: number;
        evidenceCreated: number;
        error: string | null;
        logs: string[];
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
    };
    sourceJobs: {
        id: number;
        sourceType: string;
        sourceName: string | null;
        sourceUrl: string | null;
        localFileName: string | null;
        archiveStorageUri: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        chainScope: string[] | null;
        expectedRoles: string[] | null;
        status: string;
        parserVersion: string;
        submittedBy: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    documents: never[] | {
        id: number;
        sourceJobId: number | null;
        documentType: string;
        originalName: string | null;
        storageUri: string | null;
        contentHash: string;
        mimeType: string | null;
        sizeBytes: number | null;
        extractedText: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    candidates: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    evidence: never[] | {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        evidenceType: string;
        sourceUrl: string | null;
        sourceDocumentId: number | null;
        evidenceHash: string | null;
        storageUri: string | null;
        confidenceDelta: number;
        trustTier: string;
        summary: string | null;
        payload: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
    }[];
} | null>;
export declare function createDiscoveryJob(input: unknown): Promise<{
    id: number;
    createdAt: Date;
    updatedAt: Date;
    status: string;
    entityId: number | null;
    chainCode: string | null;
    protocolId: number | null;
    discoveryType: string;
    seedAddress: string | null;
    config: Record<string, unknown>;
    candidatesCreated: number;
    evidenceCreated: number;
    error: string | null;
    logs: string[];
    createdBy: string | null;
}>;
export declare function createDiscoveryJobFromRegistry(input: unknown): Promise<{
    id: number;
    createdAt: Date;
    updatedAt: Date;
    status: string;
    entityId: number | null;
    chainCode: string | null;
    protocolId: number | null;
    discoveryType: string;
    seedAddress: string | null;
    config: Record<string, unknown>;
    candidatesCreated: number;
    evidenceCreated: number;
    error: string | null;
    logs: string[];
    createdBy: string | null;
}>;
export declare function completeDiscoveryJob(input: unknown): Promise<{
    job: {
        id: number;
        discoveryType: string;
        status: string;
        chainCode: string | null;
        seedAddress: string | null;
        entityId: number | null;
        protocolId: number | null;
        config: Record<string, unknown>;
        candidatesCreated: number;
        evidenceCreated: number;
        error: string | null;
        logs: string[];
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
    };
    sourceJobId: number;
    sourceDocumentId: number;
    rows: number;
    candidatesCreated: number;
    evidenceCreated: number;
    invalidRows: number;
    duplicates: number;
}>;
