export declare const CANDIDATE_EVIDENCE_PERMISSION = "candidate:evidence";
export declare const REGISTRY_EVIDENCE_PERMISSION = "registry:edit";
export declare function listEvidenceForCandidate(candidateId: number): Promise<{
    id: number;
    candidateId: number | null;
    registryId: number | null;
    batchId: number | null;
    evidenceType: string;
    sourceUrl: string | null;
    sourceDocumentId: number | null;
    evidenceHash: string | null;
    storageUri: string | null;
    confidenceDelta: number;
    trustTier: string;
    summary: string | null;
    payload: Record<string, unknown>;
    createdBy: string | null;
    createdAt: Date;
}[]>;
export declare function listEvidenceForRegistry(registryId: number): Promise<{
    id: number;
    candidateId: number | null;
    registryId: number | null;
    batchId: number | null;
    evidenceType: string;
    sourceUrl: string | null;
    sourceDocumentId: number | null;
    evidenceHash: string | null;
    storageUri: string | null;
    confidenceDelta: number;
    trustTier: string;
    summary: string | null;
    payload: Record<string, unknown>;
    createdBy: string | null;
    createdAt: Date;
}[]>;
export declare function listEvidenceLedger(input?: unknown): Promise<{
    evidenceRows: {
        evidence: {
            id: number;
            candidateId: number | null;
            registryId: number | null;
            batchId: number | null;
            evidenceType: string;
            sourceUrl: string | null;
            sourceDocumentId: number | null;
            evidenceHash: string | null;
            storageUri: string | null;
            confidenceDelta: number;
            trustTier: string;
            summary: string | null;
            payload: Record<string, unknown>;
            createdBy: string | null;
            createdAt: Date;
        };
        candidate: {
            id: number;
            sourceJobId: number | null;
            sourceDocumentId: number | null;
            rawAddress: string;
            normalizedAddress: string;
            chainCode: string | null;
            addressFamily: string | null;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityHint: string | null;
            protocolHint: string | null;
            roleHint: string | null;
            suggestedEntityId: number | null;
            suggestedProtocolId: number | null;
            suggestedRoleId: number | null;
            confidenceScore: number;
            qualityTier: number;
            candidateStatus: string;
            duplicateOfCandidateId: number | null;
            discoveredBy: string;
            discoveryJobId: number | null;
            evidenceCount: number;
            lastSeenBlock: number | null;
            firstSeenBlock: number | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        registry: {
            id: number;
            normalizedAddress: string;
            rawAddress: string | null;
            chainCode: string;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityId: number | null;
            protocolId: number | null;
            categoryId: number | null;
            roleId: number | null;
            componentId: number | null;
            tagsetId: number | null;
            confidenceScore: number;
            labelStatus: number;
            qualityTier: number;
            flags: number;
            metricUsage: string | null;
            validFromBlock: number | null;
            validToBlock: number | null;
            firstSeenBlock: number | null;
            lastSeenBlock: number | null;
            isActive: boolean;
            primarySourceJobId: number | null;
            approvedBatchId: number | null;
            notes: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        sourceDocument: {
            id: number;
            sourceJobId: number | null;
            documentType: string;
            originalName: string | null;
            storageUri: string | null;
            contentHash: string;
            mimeType: string | null;
            sizeBytes: number | null;
            extractedText: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
        } | null;
        sourceJob: {
            id: number;
            sourceType: string;
            sourceName: string | null;
            sourceUrl: string | null;
            localFileName: string | null;
            archiveStorageUri: string | null;
            entityHint: string | null;
            protocolHint: string | null;
            chainScope: string[] | null;
            expectedRoles: string[] | null;
            status: string;
            parserVersion: string;
            submittedBy: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        creatorEmail: string | null;
        creatorName: string | null;
    }[];
    sourceVerificationRows: {
        verification: {
            id: number;
            sourceJobId: number | null;
            sourceDocumentId: number | null;
            candidateId: number | null;
            verificationScope: string;
            sourceSheet: string | null;
            sourceUrl: string | null;
            sourceTrust: string;
            status: string;
            notes: string | null;
            verificationEvidence: Record<string, unknown>;
            verifiedBy: string | null;
            createdAt: Date;
        };
        candidate: {
            id: number;
            sourceJobId: number | null;
            sourceDocumentId: number | null;
            rawAddress: string;
            normalizedAddress: string;
            chainCode: string | null;
            addressFamily: string | null;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityHint: string | null;
            protocolHint: string | null;
            roleHint: string | null;
            suggestedEntityId: number | null;
            suggestedProtocolId: number | null;
            suggestedRoleId: number | null;
            confidenceScore: number;
            qualityTier: number;
            candidateStatus: string;
            duplicateOfCandidateId: number | null;
            discoveredBy: string;
            discoveryJobId: number | null;
            evidenceCount: number;
            lastSeenBlock: number | null;
            firstSeenBlock: number | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        sourceDocument: {
            id: number;
            sourceJobId: number | null;
            documentType: string;
            originalName: string | null;
            storageUri: string | null;
            contentHash: string;
            mimeType: string | null;
            sizeBytes: number | null;
            extractedText: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
        } | null;
        sourceJob: {
            id: number;
            sourceType: string;
            sourceName: string | null;
            sourceUrl: string | null;
            localFileName: string | null;
            archiveStorageUri: string | null;
            entityHint: string | null;
            protocolHint: string | null;
            chainScope: string[] | null;
            expectedRoles: string[] | null;
            status: string;
            parserVersion: string;
            submittedBy: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        } | null;
        verifierEmail: string | null;
        verifierName: string | null;
    }[];
    filters: {
        sort: "created_at" | "type" | "trust";
        page: number;
        pageSize: number;
        q?: string | undefined;
        evidenceType?: string | undefined;
        trustTier?: string | undefined;
        sourceTrust?: string | undefined;
        verificationStatus?: string | undefined;
        verificationScope?: string | undefined;
        sourceType?: string | undefined;
        chain?: string | undefined;
        candidateId?: number | undefined;
        registryId?: number | undefined;
        sourceJobId?: number | undefined;
        sourceDocumentId?: number | undefined;
    };
    page: number;
    pageSize: number;
    evidenceTotal: number;
    evidenceTotalPages: number;
    sourceVerificationTotal: number;
    sourceVerificationTotalPages: number;
}>;
export declare function addCandidateEvidence(input: unknown): Promise<{
    id: number;
    createdAt: Date;
    sourceUrl: string | null;
    storageUri: string | null;
    createdBy: string | null;
    sourceDocumentId: number | null;
    evidenceHash: string | null;
    batchId: number | null;
    candidateId: number | null;
    registryId: number | null;
    evidenceType: string;
    confidenceDelta: number;
    trustTier: string;
    summary: string | null;
    payload: Record<string, unknown>;
}>;
export declare function addRegistryEvidence(input: unknown): Promise<{
    id: number;
    createdAt: Date;
    sourceUrl: string | null;
    storageUri: string | null;
    createdBy: string | null;
    sourceDocumentId: number | null;
    evidenceHash: string | null;
    batchId: number | null;
    candidateId: number | null;
    registryId: number | null;
    evidenceType: string;
    confidenceDelta: number;
    trustTier: string;
    summary: string | null;
    payload: Record<string, unknown>;
}>;
