export declare function listKvBuilds(input?: unknown): Promise<{
    rows: {
        id: number;
        buildHash: string;
        dictionaryVersion: string | null;
        buildKind: string;
        baseBuildId: number | null;
        deltaParentBuildId: number | null;
        lastCommittedBatchId: number | null;
        status: string;
        rowCount: number;
        storageUri: string | null;
        manifest: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    }[];
    filters: {
        sort: "created_at" | "status" | "activated_at" | "row_count";
        page: number;
        pageSize: number;
        q?: string | undefined;
        status?: string | undefined;
        dictionaryVersion?: string | undefined;
        storage?: string | undefined;
        minRows?: number | undefined;
        maxRows?: number | undefined;
    };
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
}>;
export declare function getKvBuild(id: number): Promise<{
    id: number;
    buildHash: string;
    dictionaryVersion: string | null;
    buildKind: string;
    baseBuildId: number | null;
    deltaParentBuildId: number | null;
    lastCommittedBatchId: number | null;
    status: string;
    rowCount: number;
    storageUri: string | null;
    manifest: Record<string, unknown>;
    createdBy: string | null;
    createdAt: Date;
    activatedAt: Date | null;
}>;
export declare function getKvBuildDetail(id: number): Promise<{
    build: {
        id: number;
        buildHash: string;
        dictionaryVersion: string | null;
        buildKind: string;
        baseBuildId: number | null;
        deltaParentBuildId: number | null;
        lastCommittedBatchId: number | null;
        status: string;
        rowCount: number;
        storageUri: string | null;
        manifest: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    };
    indexManifests: {
        id: number;
        buildId: number | null;
        indexName: string;
        dictionaryVersion: string | null;
        status: string;
        rowCount: number;
        keySchemaVersion: string | null;
        valueSchemaVersion: string | null;
        namespaceId: number | null;
        metricGroupId: number | null;
        contentHash: string | null;
        storageUri: string | null;
        manifestHash: string | null;
        lastCommittedBatchId: number | null;
        metadata: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    }[];
    indexShards: {
        id: number;
        manifestId: number | null;
        shardId: string;
        shardKey: string;
        shardHash: string | null;
        storageUri: string | null;
        rowCount: number;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    membershipSnapshots: {
        id: number;
        metricGroupId: number | null;
        kvBuildId: number | null;
        metricGroupCode: string;
        dictionaryVersion: string | null;
        status: string;
        memberCount: number;
        manifestHash: string | null;
        manifest: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    }[];
    membershipRows: {
        id: number;
        snapshotId: number | null;
        metricGroupId: number | null;
        registryId: number | null;
        chainCode: string;
        normalizedAddress: string;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        membershipStatus: string;
        entityId: number | null;
        roleId: number | null;
        confidenceScore: number;
        flags: number;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    latestValidation: {
        id: number;
        buildId: number;
        compileRequestBuildId: number;
        validationType: string;
        status: string;
        dictionaryVersion: string;
        registrySnapshotHash: string;
        reportHash: string;
        report: Record<string, unknown>;
        createdAt: Date;
    } | null;
    currentActiveBuildId: number | null;
} | null>;
export declare function getActiveKvBuildDetail(): Promise<{
    build: {
        id: number;
        buildHash: string;
        dictionaryVersion: string | null;
        buildKind: string;
        baseBuildId: number | null;
        deltaParentBuildId: number | null;
        lastCommittedBatchId: number | null;
        status: string;
        rowCount: number;
        storageUri: string | null;
        manifest: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    };
    indexManifests: {
        id: number;
        buildId: number | null;
        indexName: string;
        dictionaryVersion: string | null;
        status: string;
        rowCount: number;
        keySchemaVersion: string | null;
        valueSchemaVersion: string | null;
        namespaceId: number | null;
        metricGroupId: number | null;
        contentHash: string | null;
        storageUri: string | null;
        manifestHash: string | null;
        lastCommittedBatchId: number | null;
        metadata: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    }[];
    indexShards: {
        id: number;
        manifestId: number | null;
        shardId: string;
        shardKey: string;
        shardHash: string | null;
        storageUri: string | null;
        rowCount: number;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    membershipSnapshots: {
        id: number;
        metricGroupId: number | null;
        kvBuildId: number | null;
        metricGroupCode: string;
        dictionaryVersion: string | null;
        status: string;
        memberCount: number;
        manifestHash: string | null;
        manifest: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
        activatedAt: Date | null;
    }[];
    membershipRows: {
        id: number;
        snapshotId: number | null;
        metricGroupId: number | null;
        registryId: number | null;
        chainCode: string;
        normalizedAddress: string;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        membershipStatus: string;
        entityId: number | null;
        roleId: number | null;
        confidenceScore: number;
        flags: number;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    latestValidation: {
        id: number;
        buildId: number;
        compileRequestBuildId: number;
        validationType: string;
        status: string;
        dictionaryVersion: string;
        registrySnapshotHash: string;
        reportHash: string;
        report: Record<string, unknown>;
        createdAt: Date;
    } | null;
    currentActiveBuildId: number | null;
} | null>;
export declare function createKvBuildManifest(input: unknown): Promise<{
    id: number;
    createdAt: Date;
    status: string;
    storageUri: string | null;
    createdBy: string | null;
    dictionaryVersion: string | null;
    activatedAt: Date | null;
    buildHash: string;
    buildKind: string;
    baseBuildId: number | null;
    deltaParentBuildId: number | null;
    lastCommittedBatchId: number | null;
    rowCount: number;
    manifest: Record<string, unknown>;
}>;
export declare function activateKvBuildManifest(input: unknown): Promise<{
    id: number;
    buildHash: string;
    dictionaryVersion: string | null;
    buildKind: string;
    baseBuildId: number | null;
    deltaParentBuildId: number | null;
    lastCommittedBatchId: number | null;
    status: string;
    rowCount: number;
    storageUri: string | null;
    manifest: Record<string, unknown>;
    createdBy: string | null;
    createdAt: Date;
    activatedAt: Date | null;
}>;
