export declare function listRegistry(input?: unknown): Promise<{
    rows: {
        registry: {
            id: number;
            normalizedAddress: string;
            rawAddress: string | null;
            chainCode: string;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityId: number | null;
            protocolId: number | null;
            categoryId: number | null;
            roleId: number | null;
            componentId: number | null;
            tagsetId: number | null;
            confidenceScore: number;
            labelStatus: number;
            qualityTier: number;
            flags: number;
            metricUsage: string | null;
            validFromBlock: number | null;
            validToBlock: number | null;
            firstSeenBlock: number | null;
            lastSeenBlock: number | null;
            isActive: boolean;
            primarySourceJobId: number | null;
            approvedBatchId: number | null;
            notes: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        };
        entityName: string | null;
        entityCode: string | null;
        protocolCode: string | null;
        protocolName: string | null;
        roleCode: string | null;
        categoryCode: string | null;
    }[];
    filters: {
        active: "active" | "inactive" | "historical" | "all";
        sort: "created_at" | "confidence" | "quality" | "address";
        page: number;
        pageSize: number;
        q?: string | undefined;
        chain?: string | undefined;
        entity?: string | undefined;
        protocol?: string | undefined;
        role?: string | undefined;
        category?: string | undefined;
        metricEligible?: "false" | "true" | undefined;
        minConfidence?: number | undefined;
        maxConfidence?: number | undefined;
        qualityTier?: number | undefined;
        sourceBatch?: number | undefined;
        conflicts?: "false" | "true" | undefined;
    };
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
}>;
export declare function getRegistryDetail(id: number): Promise<{
    evidence: {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        evidenceType: string;
        sourceUrl: string | null;
        sourceDocumentId: number | null;
        evidenceHash: string | null;
        storageUri: string | null;
        confidenceDelta: number;
        trustTier: string;
        summary: string | null;
        payload: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
    }[];
    sourceBatch: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        entityId: number | null;
        protocolId: number | null;
        roleId: number | null;
        sourceType: string | null;
        sourceUrl: string | null;
        sourceName: string | null;
        confidenceDefault: number | null;
        qualityTierDefault: number | null;
        statusDefault: number | null;
        flagsDefault: number | null;
        importedCount: number;
        acceptedCount: number;
        rejectedCount: number;
        conflictCount: number;
        effectiveFromBlock: number | null;
        effectiveToBlock: number | null;
        labelAction: string;
        supersedesBatchId: number | null;
        batchHash: string | null;
        evidenceHash: string | null;
        storageUri: string | null;
        parserVersion: string;
        dictionaryVersion: string | null;
        status: string;
        createdBy: string | null;
        approvedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        approvedAt: Date | null;
        committedAt: Date | null;
    };
    primarySourceJob: {
        id: number;
        sourceType: string;
        sourceName: string | null;
        sourceUrl: string | null;
        localFileName: string | null;
        archiveStorageUri: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        chainScope: string[] | null;
        expectedRoles: string[] | null;
        status: string;
        parserVersion: string;
        submittedBy: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    primarySourceDocument: {
        id: number;
        sourceJobId: number | null;
        documentType: string;
        originalName: string | null;
        storageUri: string | null;
        contentHash: string;
        mimeType: string | null;
        sizeBytes: number | null;
        extractedText: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    };
    provenanceCandidate: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        suggestedComponentId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    provenanceCandidateId: number | null;
    approvalEvents: {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        action: string;
        actorId: string | null;
        reason: string | null;
        beforeJson: Record<string, unknown> | null;
        afterJson: Record<string, unknown> | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    relatedCandidates: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        suggestedComponentId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    relatedDiscoveryJobs: {
        id: number;
        discoveryType: string;
        status: string;
        chainCode: string | null;
        seedAddress: string | null;
        entityId: number | null;
        protocolId: number | null;
        config: Record<string, unknown>;
        candidatesCreated: number;
        evidenceCreated: number;
        error: string | null;
        logs: string[];
        createdBy: string | null;
        createdAt: Date;
        updatedAt: Date;
    }[];
    relatedRegistryRows: {
        registry: {
            id: number;
            normalizedAddress: string;
            rawAddress: string | null;
            chainCode: string;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityId: number | null;
            protocolId: number | null;
            categoryId: number | null;
            roleId: number | null;
            componentId: number | null;
            tagsetId: number | null;
            confidenceScore: number;
            labelStatus: number;
            qualityTier: number;
            flags: number;
            metricUsage: string | null;
            validFromBlock: number | null;
            validToBlock: number | null;
            firstSeenBlock: number | null;
            lastSeenBlock: number | null;
            isActive: boolean;
            primarySourceJobId: number | null;
            approvedBatchId: number | null;
            notes: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        };
        entityName: string | null;
        protocolName: string | null;
        roleCode: string | null;
    }[];
    metricGroupMatches: import("../../metric-rules").MetricGroupMatchDefinition[];
    secondaryRoles: import("../../secondary-roles").RegistrySecondaryRole[];
    resolverPreview: {
        chainCode: string;
        normalizedAddress: string;
        prefixCode: number | null;
        payloadHex: string | null;
        activeLabel: boolean;
        validFromBlock: number | null;
        validToBlock: number | null;
    };
    registry: {
        id: number;
        normalizedAddress: string;
        rawAddress: string | null;
        chainCode: string;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityId: number | null;
        protocolId: number | null;
        categoryId: number | null;
        roleId: number | null;
        componentId: number | null;
        tagsetId: number | null;
        confidenceScore: number;
        labelStatus: number;
        qualityTier: number;
        flags: number;
        metricUsage: string | null;
        validFromBlock: number | null;
        validToBlock: number | null;
        firstSeenBlock: number | null;
        lastSeenBlock: number | null;
        isActive: boolean;
        primarySourceJobId: number | null;
        approvedBatchId: number | null;
        notes: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    entity: {
        id: number;
        entityCode: string;
        entityName: string;
        entityType: string | null;
        categoryId: number | null;
        websiteUrl: string | null;
        description: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null;
    protocol: {
        id: number;
        entityId: number | null;
        protocolCode: string;
        protocolName: string;
        protocolType: string | null;
        chainScope: string[] | null;
        description: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null;
    role: {
        roleId: number;
        roleCode: string;
        roleName: string;
        categoryId: number | null;
        roleGroup: string | null;
        metricUsageDefault: string | null;
        boundaryClass: string | null;
        defaultQualityTier: number;
        defaultFlags: number;
        description: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null;
    category: {
        categoryId: number;
        categoryCode: string;
        categoryName: string;
        parentCategoryId: number | null;
        domainCode: string | null;
        metricDomain: string | null;
        description: string | null;
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
    } | null;
} | null>;
export declare function updateRegistryLabel(input: unknown): Promise<{
    id: number;
    normalizedAddress: string;
    rawAddress: string | null;
    chainCode: string;
    prefixCode: number | null;
    namespaceId: number | null;
    addressCodecId: number | null;
    payloadHex: string | null;
    entityId: number | null;
    protocolId: number | null;
    categoryId: number | null;
    roleId: number | null;
    componentId: number | null;
    tagsetId: number | null;
    confidenceScore: number;
    labelStatus: number;
    qualityTier: number;
    flags: number;
    metricUsage: string | null;
    validFromBlock: number | null;
    validToBlock: number | null;
    firstSeenBlock: number | null;
    lastSeenBlock: number | null;
    isActive: boolean;
    primarySourceJobId: number | null;
    approvedBatchId: number | null;
    notes: string | null;
    metadata: Record<string, unknown>;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function addRegistrySecondaryRole(input: unknown): Promise<{
    id: number;
    normalizedAddress: string;
    rawAddress: string | null;
    chainCode: string;
    prefixCode: number | null;
    namespaceId: number | null;
    addressCodecId: number | null;
    payloadHex: string | null;
    entityId: number | null;
    protocolId: number | null;
    categoryId: number | null;
    roleId: number | null;
    componentId: number | null;
    tagsetId: number | null;
    confidenceScore: number;
    labelStatus: number;
    qualityTier: number;
    flags: number;
    metricUsage: string | null;
    validFromBlock: number | null;
    validToBlock: number | null;
    firstSeenBlock: number | null;
    lastSeenBlock: number | null;
    isActive: boolean;
    primarySourceJobId: number | null;
    approvedBatchId: number | null;
    notes: string | null;
    metadata: Record<string, unknown>;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function supersedeRegistryLabel(input: unknown): Promise<{
    id: number;
    normalizedAddress: string;
    rawAddress: string | null;
    chainCode: string;
    prefixCode: number | null;
    namespaceId: number | null;
    addressCodecId: number | null;
    payloadHex: string | null;
    entityId: number | null;
    protocolId: number | null;
    categoryId: number | null;
    roleId: number | null;
    componentId: number | null;
    tagsetId: number | null;
    confidenceScore: number;
    labelStatus: number;
    qualityTier: number;
    flags: number;
    metricUsage: string | null;
    validFromBlock: number | null;
    validToBlock: number | null;
    firstSeenBlock: number | null;
    lastSeenBlock: number | null;
    isActive: boolean;
    primarySourceJobId: number | null;
    approvedBatchId: number | null;
    notes: string | null;
    metadata: Record<string, unknown>;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function deactivateRegistryLabel(input: unknown): Promise<{
    id: number;
    normalizedAddress: string;
    rawAddress: string | null;
    chainCode: string;
    prefixCode: number | null;
    namespaceId: number | null;
    addressCodecId: number | null;
    payloadHex: string | null;
    entityId: number | null;
    protocolId: number | null;
    categoryId: number | null;
    roleId: number | null;
    componentId: number | null;
    tagsetId: number | null;
    confidenceScore: number;
    labelStatus: number;
    qualityTier: number;
    flags: number;
    metricUsage: string | null;
    validFromBlock: number | null;
    validToBlock: number | null;
    firstSeenBlock: number | null;
    lastSeenBlock: number | null;
    isActive: boolean;
    primarySourceJobId: number | null;
    approvedBatchId: number | null;
    notes: string | null;
    metadata: Record<string, unknown>;
    createdAt: Date;
    updatedAt: Date;
}>;
export declare function markRegistryHistorical(input: unknown): Promise<{
    id: number;
    normalizedAddress: string;
    rawAddress: string | null;
    chainCode: string;
    prefixCode: number | null;
    namespaceId: number | null;
    addressCodecId: number | null;
    payloadHex: string | null;
    entityId: number | null;
    protocolId: number | null;
    categoryId: number | null;
    roleId: number | null;
    componentId: number | null;
    tagsetId: number | null;
    confidenceScore: number;
    labelStatus: number;
    qualityTier: number;
    flags: number;
    metricUsage: string | null;
    validFromBlock: number | null;
    validToBlock: number | null;
    firstSeenBlock: number | null;
    lastSeenBlock: number | null;
    isActive: boolean;
    primarySourceJobId: number | null;
    approvedBatchId: number | null;
    notes: string | null;
    metadata: Record<string, unknown>;
    createdAt: Date;
    updatedAt: Date;
}>;
