export declare function listSourceJobs(input?: unknown): Promise<{
    rows: {
        id: number;
        sourceType: string;
        sourceName: string | null;
        sourceUrl: string | null;
        localFileName: string | null;
        archiveStorageUri: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        chainScope: string[] | null;
        expectedRoles: string[] | null;
        status: string;
        parserVersion: string;
        submittedBy: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    filters: {
        sort: "created_at" | "updated_at" | "source_type" | "status";
        page: number;
        pageSize: number;
        q?: string | undefined;
        sourceType?: string | undefined;
        status?: string | undefined;
        entity?: string | undefined;
        protocol?: string | undefined;
        chain?: string | undefined;
    };
    total: number;
    page: number;
    pageSize: number;
    totalPages: number;
}>;
export declare function getSourceJob(id: number): Promise<{
    sourceJob: {
        id: number;
        sourceType: string;
        sourceName: string | null;
        sourceUrl: string | null;
        localFileName: string | null;
        archiveStorageUri: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        chainScope: string[] | null;
        expectedRoles: string[] | null;
        status: string;
        parserVersion: string;
        submittedBy: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    };
    documents: {
        id: number;
        sourceJobId: number | null;
        documentType: string;
        originalName: string | null;
        storageUri: string | null;
        contentHash: string;
        mimeType: string | null;
        sizeBytes: number | null;
        extractedText: string | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
    }[];
    candidates: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        rawAddress: string;
        normalizedAddress: string;
        chainCode: string | null;
        addressFamily: string | null;
        prefixCode: number | null;
        namespaceId: number | null;
        addressCodecId: number | null;
        payloadHex: string | null;
        entityHint: string | null;
        protocolHint: string | null;
        roleHint: string | null;
        suggestedEntityId: number | null;
        suggestedProtocolId: number | null;
        suggestedRoleId: number | null;
        suggestedComponentId: number | null;
        confidenceScore: number;
        qualityTier: number;
        candidateStatus: string;
        duplicateOfCandidateId: number | null;
        discoveredBy: string;
        discoveryJobId: number | null;
        evidenceCount: number;
        lastSeenBlock: number | null;
        firstSeenBlock: number | null;
        metadata: Record<string, unknown>;
        createdAt: Date;
        updatedAt: Date;
    }[];
    verifications: {
        verification: {
            id: number;
            sourceJobId: number | null;
            sourceDocumentId: number | null;
            candidateId: number | null;
            verificationScope: string;
            sourceSheet: string | null;
            sourceUrl: string | null;
            sourceTrust: string;
            status: string;
            notes: string | null;
            verificationEvidence: Record<string, unknown>;
            verifiedBy: string | null;
            createdAt: Date;
        };
        verifierEmail: string | null;
        verifierName: string | null;
    }[];
    evidence: {
        id: number;
        candidateId: number | null;
        registryId: number | null;
        batchId: number | null;
        evidenceType: string;
        sourceUrl: string | null;
        sourceDocumentId: number | null;
        evidenceHash: string | null;
        storageUri: string | null;
        confidenceDelta: number;
        trustTier: string;
        summary: string | null;
        payload: Record<string, unknown>;
        createdBy: string | null;
        createdAt: Date;
    }[];
    downstreamBatches: {
        id: number;
        sourceJobId: number | null;
        sourceDocumentId: number | null;
        entityId: number | null;
        protocolId: number | null;
        roleId: number | null;
        sourceType: string | null;
        sourceUrl: string | null;
        sourceName: string | null;
        confidenceDefault: number | null;
        qualityTierDefault: number | null;
        statusDefault: number | null;
        flagsDefault: number | null;
        importedCount: number;
        acceptedCount: number;
        rejectedCount: number;
        conflictCount: number;
        effectiveFromBlock: number | null;
        effectiveToBlock: number | null;
        labelAction: string;
        supersedesBatchId: number | null;
        batchHash: string | null;
        evidenceHash: string | null;
        storageUri: string | null;
        parserVersion: string;
        dictionaryVersion: string | null;
        status: string;
        createdBy: string | null;
        approvedBy: string | null;
        createdAt: Date;
        updatedAt: Date;
        approvedAt: Date | null;
        committedAt: Date | null;
    }[];
    downstreamRegistryRows: {
        registry: {
            id: number;
            normalizedAddress: string;
            rawAddress: string | null;
            chainCode: string;
            prefixCode: number | null;
            namespaceId: number | null;
            addressCodecId: number | null;
            payloadHex: string | null;
            entityId: number | null;
            protocolId: number | null;
            categoryId: number | null;
            roleId: number | null;
            componentId: number | null;
            tagsetId: number | null;
            confidenceScore: number;
            labelStatus: number;
            qualityTier: number;
            flags: number;
            metricUsage: string | null;
            validFromBlock: number | null;
            validToBlock: number | null;
            firstSeenBlock: number | null;
            lastSeenBlock: number | null;
            isActive: boolean;
            primarySourceJobId: number | null;
            approvedBatchId: number | null;
            notes: string | null;
            metadata: Record<string, unknown>;
            createdAt: Date;
            updatedAt: Date;
        };
        entityName: string | null;
        protocolName: string | null;
        roleCode: string | null;
    }[];
    documentRollup: {
        totalDocuments: number;
        withStorageUri: number;
        missingStorageUri: number;
        withContentHash: number;
        missingContentHash: number;
        withExtractedText: number;
        totalSizeBytes: number;
        typeDistribution: import("../../batch-detail").DistributionRow[];
    };
    candidateRollup: {
        totalCandidates: number;
        evidenceCount: number;
        approvedCount: number;
        pendingCount: number;
        duplicateCount: number;
        conflictCount: number;
        statusDistribution: import("../../batch-detail").DistributionRow[];
        chainDistribution: import("../../batch-detail").DistributionRow[];
        confidenceDistribution: import("../../batch-detail").DistributionRow[];
    };
    evidenceRollup: {
        totalEvidence: number;
        typeDistribution: import("../../batch-detail").DistributionRow[];
        trustDistribution: import("../../batch-detail").DistributionRow[];
    };
    verificationRollup: {
        totalVerifications: number;
        verifiedCount: number;
        nonVerifiedCount: number;
        scopeDistribution: import("../../batch-detail").DistributionRow[];
        trustDistribution: import("../../batch-detail").DistributionRow[];
        statusDistribution: import("../../batch-detail").DistributionRow[];
    };
    downstreamRollup: {
        totalBatches: number;
        committedBatches: number;
        totalRegistryRows: number;
        activeRegistryRows: number;
        inactiveRegistryRows: number;
        batchStatusDistribution: import("../../batch-detail").DistributionRow[];
    };
} | null>;
export declare function recordSourceVerification(input: unknown): Promise<{
    id: number;
    createdAt: Date;
    sourceUrl: string | null;
    status: string;
    sourceJobId: number | null;
    notes: string | null;
    sourceDocumentId: number | null;
    candidateId: number | null;
    verificationScope: string;
    sourceSheet: string | null;
    sourceTrust: string;
    verificationEvidence: Record<string, unknown>;
    verifiedBy: string | null;
}>;
export declare function archiveSourceJob(input: unknown): Promise<{
    id: number;
    sourceType: string;
    sourceName: string | null;
    sourceUrl: string | null;
    localFileName: string | null;
    archiveStorageUri: string | null;
    entityHint: string | null;
    protocolHint: string | null;
    chainScope: string[] | null;
    expectedRoles: string[] | null;
    status: string;
    parserVersion: string;
    submittedBy: string | null;
    metadata: Record<string, unknown>;
    createdAt: Date;
    updatedAt: Date;
}>;

export type SourceJobDeletionCounts = {
    sourceDocuments: number;
    candidates: number;
    approvedCandidates: number;
    evidence: number;
    verifications: number;
    batches: number;
    protectedBatches: number;
    registryRows: number;
    kvBuildReferences: number;
};

export type SourceJobDeletionPreview = {
    sourceJobId: number;
    sourceName: string | null;
    sourceStatus: string;
    deletable: boolean;
    blockers: string[];
    counts: SourceJobDeletionCounts;
};

export declare function getSourceJobDeletionPreview(sourceJobId: number): Promise<SourceJobDeletionPreview>;
export declare function deletePendingSourceJob(input: unknown): Promise<{
    sourceJobId: number;
    deletedCounts: SourceJobDeletionCounts;
}>;
